In [1]:
#라이브러리 호출
import numpy as np
import pandas as pd

### 1025 handling csv

+ csv reader 
+ csv writer

In [2]:
'''
with open("C:\Users\Aerry Choi\Desktop\Demographic_Statistics_By_Zip_Code.csv") as infile:
    data = list(csv.reader(infile))

countParticipantsIndex = data[0].index("COUNT PARTICIPANTS")
print(countParticipantsIndex)
'''

"""
import statistics
countParticipants = [int(row[countParticipantsIndex]) for row in data [1:]]
print(statistics.mean(countParticipants), statistics.stdev(countParticipants))
'''

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-2-41f33400d4b1>, line 13)

+ pymysql
+ conn = pymysql.connect(host='localhost',port=3306, user ="user", passwd="badpassword", db="dsdb") 
+ cur = conn.cursor() 
+ query ='select movie.title, movie.length, movie.movie_id from movie where movie_id >5 order by movie.length' 
+ n_rows = cur.execute(query) 
+ results = list(cur.fetchall()) 
+ print(results)

### 1027 numpy, pandas

In [3]:
numbers =np.array(range(1,11), copy=True)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
np.ones([1,1])

array([[ 1.]])

In [5]:
print(np.ones([3,2]))

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [6]:
ones = np.ones([2,4], dtype=np.float64)
print(ones)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [7]:
empty = np.empty([2,4],dtype=np.float64)
print(empty)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [8]:
ones = np.ones([2,4], dtype=np.float64)
print(ones.shape)

(2, 4)


In [9]:
ones = np.ones([2,4], dtype=np.float64)
print(ones.ndim)

2


In [10]:
ones = np.ones([2,4], dtype=np.float64)
print(ones.dtype)

float64


In [11]:
eye = np.eye(3, k=0)
print(eye)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
print(np.eye(5, k=0))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [13]:
test_array = [[1,1,1,1],
              [1,1,1,1]]

In [14]:
print(test_array)

[[1, 1, 1, 1], [1, 1, 1, 1]]


In [15]:
np.ndim(test_array)

2

In [16]:
np.shape(test_array)

(2, 4)

In [17]:
inflation = pd.Series((2.2,3.4,2.8,1.6,2.3,2.7,3.4,3.2,2.8,3.8,-0.4,1.6,3.2,2.1,1.5,1.5))

In [18]:
print(inflation)

0     2.2
1     3.4
2     2.8
3     1.6
4     2.3
5     2.7
6     3.4
7     3.2
8     2.8
9     3.8
10   -0.4
11    1.6
12    3.2
13    2.1
14    1.5
15    1.5
dtype: float64


In [19]:
len(inflation)

16

In [20]:
inflation.values

array([ 2.2,  3.4,  2.8,  1.6,  2.3,  2.7,  3.4,  3.2,  2.8,  3.8, -0.4,
        1.6,  3.2,  2.1,  1.5,  1.5])

In [21]:
inflation.index

RangeIndex(start=0, stop=16, step=1)

In [22]:
inflation.values[-1]

1.5

In [23]:
inflation.index = pd.Index(range(1999,2015))

In [24]:
print(inflation)

1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
2004    2.7
2005    3.4
2006    3.2
2007    2.8
2008    3.8
2009   -0.4
2010    1.6
2011    3.2
2012    2.1
2013    1.5
2014    1.5
dtype: float64


In [25]:
inflation.index.name = "Year"

In [26]:
inflation.name = "inflation"

In [27]:
print(inflation.head())

Year
1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
Name: inflation, dtype: float64


In [28]:
print(len(inflation))

16


In [29]:
#alcohol data
alco2009 = pd.read_csv('C:/Users/Administrator/Desktop/Business Prog/biz_final/example_file/example1027/report2009.csv',index_col="State")

In [30]:
alco2009["Total"] = 0
print(alco2009)


                      Beer  Wine  Spirits  Total
State                                           
Alabama               1.20  0.22     0.58      0
Alaska                1.31  0.54     1.16      0
Arizona               1.19  0.38     0.74      0
Arkansas              1.07  0.17     0.60      0
California            1.05  0.55     0.73      0
Colorado              1.22  0.46     1.00      0
Connecticut           0.89  0.59     0.86      0
Delaware              1.31  0.57     1.25      0
District of Columbia  1.26  1.00     1.64      0
Florida               1.21  0.48     0.92      0
Georgia               1.08  0.25     0.64      0
Hawaii                1.30  0.53     0.75      0
Idaho                 1.05  0.92     0.70      0
Illinois              1.22  0.39     0.73      0
Indiana               1.09  0.25     0.73      0
Iowa                  1.42  0.18     0.72      0
Kansas                1.18  0.14     0.67      0
Kentucky              1.11  0.18     0.65      0
Louisiana           

In [31]:
alco2009.columns.values

array(['Beer', 'Wine', 'Spirits', 'Total'], dtype=object)

In [32]:
alco2009.index.values

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
       'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
       'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming'], dtype=object)

In [33]:
print(alco2009.reset_index().set_index('Beer').head())

           State  Wine  Spirits  Total
Beer                                  
1.20     Alabama  0.22     0.58      0
1.31      Alaska  0.54     1.16      0
1.19     Arizona  0.38     0.74      0
1.07    Arkansas  0.17     0.60      0
1.05  California  0.55     0.73      0


In [34]:
alco2009.reset_index().set_index('Beer').head()

State  Wine  Spirits  Total
Beer                                  
1.20     Alabama  0.22     0.58      0
1.31      Alaska  0.54     1.16      0
1.19     Arizona  0.38     0.74      0
1.07    Arkansas  0.17     0.60      0
1.05  California  0.55     0.73      0

In [35]:
print(alco2009.ix["Nebraska"])

Beer       1.46
Wine       0.20
Spirits    0.68
Total      0.00
Name: Nebraska, dtype: float64


c:\program files\anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


In [36]:
print("Samoa" in alco2009.index)

False


In [37]:
#re-indexing
s_states = [state for state in alco2009.index if state[0] == "S"] + ["Samoa"]

In [38]:
drinks = list(alco2009.columns)+["Water"]

In [39]:
nan_alco = alco2009.reindex(s_states, columns = drinks)

In [40]:
print(nan_alco)

                Beer  Wine  Spirits  Total  Water
State                                            
South Carolina  1.36  0.24     0.77    0.0    NaN
South Dakota    1.53  0.22     0.88    0.0    NaN
Samoa            NaN   NaN      NaN    NaN    NaN


In [41]:
#hierarchical indexing
alco = pd.read_csv("C:/Users/Administrator/Desktop/Business Prog/biz_final/example_file/example1027/report.csv", index_col = ["State", "Year"])

In [42]:
print(alco.head(10))

              Beer  Wine  Spirits
State   Year                     
Alabama 1977  0.99  0.13     0.84
        1978  0.98  0.12     0.88
        1979  0.98  0.12     0.84
        1980  0.96  0.16     0.74
        1981  1.00  0.19     0.73
        1982  1.00  0.18     0.72
        1983  1.01  0.17     0.71
        1984  1.02  0.19     0.69
        1985  1.06  0.17     0.67
        1986  1.09  0.18     0.64


In [43]:
#stacking
alco.head()

Beer  Wine  Spirits
State   Year                     
Alabama 1977  0.99  0.13     0.84
        1978  0.98  0.12     0.88
        1979  0.98  0.12     0.84
        1980  0.96  0.16     0.74
        1981  1.00  0.19     0.73

In [44]:
tall_alco = alco.stack()

In [45]:
tall_alco

State    Year         
Alabama  1977  Beer       0.99
               Wine       0.13
               Spirits    0.84
         1978  Beer       0.98
               Wine       0.12
               Spirits    0.88
         1979  Beer       0.98
               Wine       0.12
               Spirits    0.84
         1980  Beer       0.96
               Wine       0.16
               Spirits    0.74
         1981  Beer       1.00
               Wine       0.19
               Spirits    0.73
         1982  Beer       1.00
               Wine       0.18
               Spirits    0.72
         1983  Beer       1.01
               Wine       0.17
               Spirits    0.71
         1984  Beer       1.02
               Wine       0.19
               Spirits    0.69
         1985  Beer       1.06
               Wine       0.17
               Spirits    0.67
         1986  Beer       1.09
               Wine       0.18
               Spirits    0.64
                          ... 
Wyoming  2000  B

In [46]:
tall_alco.index.names = ['State','Year','Drink']

In [47]:
print(tall_alco.head(10))

State    Year  Drink  
Alabama  1977  Beer       0.99
               Wine       0.13
               Spirits    0.84
         1978  Beer       0.98
               Wine       0.12
               Spirits    0.88
         1979  Beer       0.98
               Wine       0.12
               Spirits    0.84
         1980  Beer       0.96
dtype: float64


In [48]:
#pivoting
alco = pd.read_csv("C:/Users/Administrator/Desktop/Business Prog/biz_final/example_file/example1027/report.csv")
print(alco.pivot("Year","State","Wine"))

State  Alabama  Alaska  Arizona  Arkansas  California  Colorado  Connecticut  \
Year                                                                           
1977      0.13    0.42     0.34      0.10        0.67      0.36         0.35   
1978      0.12    0.45     0.37      0.11        0.68      0.47         0.38   
1979      0.12    0.47     0.39      0.10        0.70      0.47         0.40   
1980      0.16    0.50     0.36      0.12        0.71      0.47         0.43   
1981      0.19    0.57     0.42      0.12        0.72      0.44         0.44   
1982      0.18    0.56     0.40      0.12        0.72      0.46         0.49   
1983      0.17    0.61     0.44      0.13        0.75      0.46         0.49   
1984      0.19    0.58     0.45      0.12        0.74      0.46         0.50   
1985      0.17    0.58     0.46      0.13        0.78      0.50         0.50   
1986      0.18    0.56     0.46      0.09        0.79      0.46         0.51   
1987      0.18    0.54     0.46      0.1

### 1101 SQL

+ 지난 시간 복습 .. SQL, create table, insert, select, update, delete, JOIN  

### 1103 missing value

In [49]:
alco2009 = pd.read_csv("C:/Users/Administrator/Desktop/Business Prog/biz_final/example_file/example1027/report2009.csv", 
                       index_col = "State")
s_states = [state for state in alco2009.index if state[0] == "S"] + ["Samoa"]
drinks = list(alco2009.columns)+["Water"]
nan_alco = alco2009.reindex(s_states, columns = drinks)

In [50]:
s_states

['South Carolina', 'South Dakota', 'Samoa']

In [51]:
drinks

['Beer', 'Wine', 'Spirits', 'Water']

In [52]:
nan_alco

Beer  Wine  Spirits  Water
State                                     
South Carolina  1.36  0.24     0.77    NaN
South Dakota    1.53  0.22     0.88    NaN
Samoa            NaN   NaN      NaN    NaN

In [53]:
##Deleting Missing values
row_delete_nan_alco=nan_alco.dropna(how="all")
print(row_delete_nan_alco)

                Beer  Wine  Spirits  Water
State                                     
South Carolina  1.36  0.24     0.77    NaN
South Dakota    1.53  0.22     0.88    NaN


In [54]:
print(nan_alco)

                Beer  Wine  Spirits  Water
State                                     
South Carolina  1.36  0.24     0.77    NaN
South Dakota    1.53  0.22     0.88    NaN
Samoa            NaN   NaN      NaN    NaN


In [55]:
col_delete_nan_alco=nan_alco.dropna(how="all", axis=1)
print(col_delete_nan_alco)

                Beer  Wine  Spirits
State                              
South Carolina  1.36  0.24     0.77
South Dakota    1.53  0.22     0.88
Samoa            NaN   NaN      NaN


In [56]:
##Deleting Columns
alco2009 = pd.read_csv("C:/Users/Administrator/Desktop/Business Prog/biz_final/example_file/example1027/report2009.csv"
                       , index_col = "State")
df = alco2009.drop("Alabama")
print(df)

                      Beer  Wine  Spirits
State                                    
Alaska                1.31  0.54     1.16
Arizona               1.19  0.38     0.74
Arkansas              1.07  0.17     0.60
California            1.05  0.55     0.73
Colorado              1.22  0.46     1.00
Connecticut           0.89  0.59     0.86
Delaware              1.31  0.57     1.25
District of Columbia  1.26  1.00     1.64
Florida               1.21  0.48     0.92
Georgia               1.08  0.25     0.64
Hawaii                1.30  0.53     0.75
Idaho                 1.05  0.92     0.70
Illinois              1.22  0.39     0.73
Indiana               1.09  0.25     0.73
Iowa                  1.42  0.18     0.72
Kansas                1.18  0.14     0.67
Kentucky              1.11  0.18     0.65
Louisiana             1.50  0.28     0.85
Maine                 1.24  0.42     0.83
Maryland              0.97  0.37     0.87
Massachusetts         1.02  0.61     0.84
Michigan              1.10  0.31  

In [57]:
df = alco2009.drop("Beer", axis = 1)
print(df)

                      Wine  Spirits
State                              
Alabama               0.22     0.58
Alaska                0.54     1.16
Arizona               0.38     0.74
Arkansas              0.17     0.60
California            0.55     0.73
Colorado              0.46     1.00
Connecticut           0.59     0.86
Delaware              0.57     1.25
District of Columbia  1.00     1.64
Florida               0.48     0.92
Georgia               0.25     0.64
Hawaii                0.53     0.75
Idaho                 0.92     0.70
Illinois              0.39     0.73
Indiana               0.25     0.73
Iowa                  0.18     0.72
Kansas                0.14     0.67
Kentucky              0.18     0.65
Louisiana             0.28     0.85
Maine                 0.42     0.83
Maryland              0.37     0.87
Massachusetts         0.61     0.84
Michigan              0.31     0.80
Minnesota             0.37     1.04
Mississippi           0.11     0.71
Missouri              0.30  

In [58]:
##Replacing Missing values
isnull=nan_alco.isnull()
print(isnull)

                 Beer   Wine  Spirits  Water
State                                       
South Carolina  False  False    False   True
South Dakota    False  False    False   True
Samoa            True   True     True   True


In [59]:
sp = nan_alco['Spirits']
clean = sp.notnull()

In [60]:
sp

State
South Carolina    0.77
South Dakota      0.88
Samoa              NaN
Name: Spirits, dtype: float64

In [61]:
clean

State
South Carolina     True
South Dakota       True
Samoa             False
Name: Spirits, dtype: bool

In [62]:
-clean

State
South Carolina    False
South Dakota      False
Samoa              True
Name: Spirits, dtype: bool

In [63]:
sp[-clean]

State
Samoa   NaN
Name: Spirits, dtype: float64

In [64]:
sp[clean]

State
South Carolina    0.77
South Dakota      0.88
Name: Spirits, dtype: float64

In [65]:
sp[-clean]=sp[clean].mean()
print(nan_alco)

                Beer  Wine  Spirits  Water
State                                     
South Carolina  1.36  0.24    0.770    NaN
South Dakota    1.53  0.22    0.880    NaN
Samoa            NaN   NaN    0.825    NaN


In [66]:
fill = nan_alco.fillna(0)
print(fill)

                Beer  Wine  Spirits  Water
State                                     
South Carolina  1.36  0.24    0.770    0.0
South Dakota    1.53  0.22    0.880    0.0
Samoa           0.00  0.00    0.825    0.0
